version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
  opencart:
    build: 'docker/'
    volumes:
      - '.:/source'
      - '${BUILD_ARTIFACT:-undefined}:/dist/paymentgatewaycloud.zip'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - SCHEMA=http
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - WHITELABEL=${WHITELABEL:-}
      - BITNAMI_APP_NAME=${BITNAMI_APP_NAME:-opencart}
      - BITNAMI_IMAGE_VERSION=${BITNAMI_IMAGE_VERSION:-latest}
      - MARIADB_HOST=${MARIADB_HOST:-mariadb}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER:-3306}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER:-root}
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MYSQL_CLIENT_CREATE_DATABASE_NAME}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=${MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES:-ALL}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MYSQL_CLIENT_CREATE_DATABASE_USER}
      - OPENCART_DATABASE_NAME=${OPENCART_DATABASE_NAME:-bitnami_opencart}
      - OPENCART_DATABASE_PASSWORD=${OPENCART_DATABASE_PASSWORD}
      - OPENCART_DATABASE_USER=${OPENCART_DATABASE_USER:-bn_opencart}
      - OPENCART_EMAIL=${OPENCART_EMAIL:-user@example.com}
      - OPENCART_HOST=${OPENCART_HOST:-localhost}
      - OPENCART_HTTP_TIMEOUT=${OPENCART_HTTP_TIMEOUT:-120}
      - OPENCART_PASSWORD=${OPENCART_PASSWORD:-bitnami1}
      - REPOSITORY=${REPOSITORY:-https://github.com/user/repo}
      - OPENCART_USERNAME=${OPENCART_USERNAME:-user}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_USER=${SMTP_USER}
      - PRECONFIGURE=${PRECONFIGURE}
      - DEMO_CUSTOMER_PASSWORD=${DEMO_CUSTOMER_PASSWORD:-customer}
      - SHOP_PGC_URL=${SHOP_PGC_URL:-sandbox}
      - SHOP_PGC_USER=${SHOP_PGC_USER:-test-user}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD:-test-pass}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY:-key}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET:-secret}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY:-int_key}
      - SHOP_PGC_CC_ENABLED=${SHOP_PGC_CC_ENABLED:-1}
      - SHOP_PGC_CC_MODE=${SHOP_PGC_CC_MODE:-debit}
      - SHOP_PGC_CC_SEAMLESS=${SHOP_PGC_CC_SEAMLESS:-0}
      - SHOP_PGC_CC_AMEX=${SHOP_PGC_CC_AMEX:-1}
      - SHOP_PGC_CC_AMEX_MODE=${SHOP_PGC_CC_AMEX_MODE:-debit}
      - SHOP_PGC_CC_AMEX_SEAMLESS=${SHOP_PGC_CC_AMEX_SEAMLESS:-0}
      - SHOP_PGC_CC_DINERS=${SHOP_PGC_CC_DINERS:-1}
      - SHOP_PGC_CC_DINERS_MODE=${SHOP_PGC_CC_DINERS_MODE:-preauthorize}
      - SHOP_PGC_CC_DINERS_SEAMLESS=${SHOP_PGC_CC_DINERS_SEAMLESS:-0}
      - SHOP_PGC_CC_DISCOVER=${SHOP_PGC_CC_DISCOVER:-1}
      - SHOP_PGC_CC_DISCOVER_MODE=${SHOP_PGC_CC_DISCOVER_MODE:-debit}
      - SHOP_PGC_CC_DISCOVER_SEAMLESS=${SHOP_PGC_CC_DISCOVER_SEAMLESS:-1}
      - SHOP_PGC_CC_JCB=${SHOP_PGC_CC_JCB:-1}
      - SHOP_PGC_CC_JCB_MODE=${SHOP_PGC_CC_JCB_MODE:-debit}
      - SHOP_PGC_CC_JCB_SEAMLESS=${SHOP_PGC_CC_JCB_SEAMLESS:-1}
      - SHOP_PGC_CC_MAESTRO=${SHOP_PGC_CC_MAESTRO:-1}
      - SHOP_PGC_CC_MAESTRO_MODE=${SHOP_PGC_CC_MAESTRO_MODE:-debit}
      - SHOP_PGC_CC_MAESTRO_SEAMLESS=${SHOP_PGC_CC_MAESTRO_SEAMLESS:-1}
      - SHOP_PGC_CC_MASTERCARD=${SHOP_PGC_CC_MASTERCARD:-1}
      - SHOP_PGC_CC_MASTERCARD_MODE=${SHOP_PGC_CC_MASTERCARD_MODE:-debit}
      - SHOP_PGC_CC_MASTERCARD_SEAMLESS=${SHOP_PGC_CC_MASTERCARD_SEAMLESS:-1}
      - SHOP_PGC_CC_UNIONPAY=${SHOP_PGC_CC_UNIONPAY:-1}
      - SHOP_PGC_CC_UNIONPAY_MODE=${SHOP_PGC_CC_UNIONPAY_MODE:-preauthorize}
      - SHOP_PGC_CC_UNIONPAY_SEAMLESS=${SHOP_PGC_CC_UNIONPAY_SEAMLESS:-1}
      - SHOP_PGC_CC_VISA=${SHOP_PGC_CC_VISA:-1}
      - SHOP_PGC_CC_VISA_MODE=${SHOP_PGC_CC_VISA_MODE:-preauthorize}
      - SHOP_PGC_CC_VISA_SEAMLESS=${SHOP_PGC_CC_VISA_SEAMLESS:-1}
      - BUILD_ARTIFACT=${BUILD_ARTIFACT:-undefined}

volumes:
  undefined: