version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
  opencart:
    build: 'docker/'
    volumes:
      - '.:/source'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
    - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    - BITNAMI_APP_NAME=${BITNAMI_APP_NAME}
    - BITNAMI_IMAGE_VERSION=${BITNAMI_IMAGE_VERSION}
    - MARIADB_HOST=${MARIADB_HOST}
    - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
    - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MYSQL_CLIENT_CREATE_DATABASE_NAME}
    - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
    - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=${MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES}
    - MYSQL_CLIENT_CREATE_DATABASE_USER=${MYSQL_CLIENT_CREATE_DATABASE_USER}
    - OPENCART_DATABASE_NAME=${OPENCART_DATABASE_NAME}
    - OPENCART_DATABASE_PASSWORD=${OPENCART_DATABASE_PASSWORD}
    - OPENCART_DATABASE_USER=${OPENCART_DATABASE_USER}
    - OPENCART_EMAIL=${OPENCART_EMAIL}
    - OPENCART_HOST=${OPENCART_HOST}
    - OPENCART_HTTP_TIMEOUT=${OPENCART_HTTP_TIMEOUT}
    - OPENCART_PASSWORD=${OPENCART_PASSWORD}
    - REPOSITORY=${REPOSITORY}
    - OPENCART_USERNAME=${OPENCART_USERNAME}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_PROTOCOL=${SMTP_PROTOCOL}
    - SMTP_USER=${SMTP_USER}
    - PRECONFIGURE=${PRECONFIGURE}
    - SHOP_PGC_URL=${SHOP_PGC_URL}
    - SHOP_PGC_USER=${SHOP_PGC_USER}
    - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD}
    - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY}
    - SHOP_PGC_SECRET=${SHOP_PGC_SECRET}
    - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY}
    - SHOP_PGC_CC_ENABLED=${SHOP_PGC_CC_ENABLED}
    - SHOP_PGC_CC_MODE=${SHOP_PGC_CC_MODE}
    - SHOP_PGC_CC_SEAMLESS=${SHOP_PGC_CC_SEAMLESS}
    - SHOP_PGC_CC_AMEX=${SHOP_PGC_CC_AMEX}
    - SHOP_PGC_CC_AMEX_MODE=${SHOP_PGC_CC_AMEX_MODE}
    - SHOP_PGC_CC_AMEX_SEAMLESS=${SHOP_PGC_CC_AMEX_SEAMLESS}
    - SHOP_PGC_CC_DINERS=${SHOP_PGC_CC_DINERS}
    - SHOP_PGC_CC_DINERS_MODE=${SHOP_PGC_CC_DINERS_MODE}
    - SHOP_PGC_CC_DINERS_SEAMLESS=${SHOP_PGC_CC_DINERS_SEAMLESS}
    - SHOP_PGC_CC_DISCOVER=${SHOP_PGC_CC_DISCOVER}
    - SHOP_PGC_CC_DISCOVER_MODE=${SHOP_PGC_CC_DISCOVER_MODE}
    - SHOP_PGC_CC_DISCOVER_SEAMLESS=${SHOP_PGC_CC_DISCOVER_SEAMLESS}
    - SHOP_PGC_CC_JCB=${SHOP_PGC_CC_JCB}
    - SHOP_PGC_CC_JCB_MODE=${SHOP_PGC_CC_JCB_MODE}
    - SHOP_PGC_CC_JCB_SEAMLESS=${SHOP_PGC_CC_JCB_SEAMLESS}
    - SHOP_PGC_CC_MAESTRO=${SHOP_PGC_CC_MAESTRO}
    - SHOP_PGC_CC_MAESTRO_MODE=${SHOP_PGC_CC_MAESTRO_MODE}
    - SHOP_PGC_CC_MAESTRO_SEAMLESS=${SHOP_PGC_CC_MAESTRO_SEAMLESS}
    - SHOP_PGC_CC_MASTERCARD=${SHOP_PGC_CC_MASTERCARD}
    - SHOP_PGC_CC_MASTERCARD_MODE=${SHOP_PGC_CC_MASTERCARD_MODE}
    - SHOP_PGC_CC_MASTERCARD_SEAMLESS=${SHOP_PGC_CC_MASTERCARD_SEAMLESS}
    - SHOP_PGC_CC_UNIOPNPAY=${SHOP_PGC_CC_UNIOPNPAY}
    - SHOP_PGC_CC_UNIONPAY_MODE=${SHOP_PGC_CC_UNIONPAY_MODE}
    - SHOP_PGC_CC_UNIOPNPAY_SEAMLESS=${SHOP_PGC_CC_UNIOPNPAY_SEAMLESS}
    - SHOP_PGC_CC_VISA=${SHOP_PGC_CC_VISA}
    - SHOP_PGC_CC_VISA_MODE=${SHOP_PGC_CC_VISA_MODE}
    - SHOP_PGC_CC_VISA_SEAMLESS=${SHOP_PGC_CC_VISA_SEAMLESS}
    - BUILD_ARTIFACT=${BUILD_ARTIFACT}

volumes:
  undefined: