version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
  opencart:
    build: 'docker/'
    volumes:
      - '.:/source'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - BRANCH=master
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - OPENCART_PASSWORD=CHANGEME
      - ALLOW_EMPTY_PASSWORD=yes
      - SHOP_PGC_URL=sandbox
      - SHOP_PGC_USER=test-user
      - SHOP_PGC_PASSWORD=test-pass
      - SHOP_PGC_API_KEY=test-key
      - SHOP_PGC_SECRET=test-secret
      - SHOP_PGC_INTEGRATION_KEY=test-int-key
      - SHOP_PGC_CC_ENABLED=1
      - SHOP_PGC_CC_MODE=debit
      - SHOP_PGC_CC_AMEX_MODE=preauthorize
      - SHOP_PGC_CC_DINERS_MODE=preauthorize
      - SHOP_PGC_CC_DISCOVER_MODE=preauthorize
      - SHOP_PGC_CC_MAESTRO_MODE=preauthorize
      - SHOP_PGC_CC_MASTERCARD_MODE=preauthorize
      - SHOP_PGC_CC_UNIONPAY_MODE=preauthorize
      - SHOP_PGC_CC_VISA_MODE=preauthorize
      - SHOP_PGC_CC_SEAMLESS=0
      - SHOP_PGC_CC_AMEX=1
      - SHOP_PGC_CC_AMEX_SEAMLESS=1
      - SHOP_PGC_CC_DINERS=1
      - SHOP_PGC_CC_DINERS_SEAMLESS=1
      - SHOP_PGC_CC_DISCOVER=1
      - SHOP_PGC_CC_DISCOVER_SEAMLESS=1
      - SHOP_PGC_CC_JCB=1
      - SHOP_PGC_CC_JCB_SEAMLESS=1
      - SHOP_PGC_CC_MAESTRO=1
      - SHOP_PGC_CC_MAESTRO_SEAMLESS=1
      - SHOP_PGC_CC_MASTERCARD=1
      - SHOP_PGC_CC_MASTERCARD_SEAMLESS=1
      - SHOP_PGC_CC_UNIOPNPAY=1
      - SHOP_PGC_CC_UNIOPNPAY_SEAMLESS=1
      - SHOP_PGC_CC_VISA=1
      - SHOP_PGC_CC_VISA_SEAMLES=1